### ISSUE TITLE
크롤링에 대한 아이디어 회의 @wikibootup

### ISSUE THREAD

**Issue by jinwookim0** [dobestan/maternity#4]
## Crawling URL

http://shjw.or.kr/bbs/board.php?bo_table=postnataldb&sca=서울시page=4
sca= [서울시, 인천시, 경기도, 강원도, 충청도, 경상도, 부산시, 전라도, 제주도]

http://shjw.or.kr/bbs/board.php?bo_table=postnataldb&page=1
전체보기 페이지

http://www.shj.or.kr/default/store/store_01.php?&com_board_page=1
store_ = [01, 02, …, 09] -> 서인경충강경부전제
## 중복 처리

```
1. 이름이 같은 산후조리원에 대해
2. 주소를 분리 ( 시부터 동까지 )
3. 이름 앞에 구분할 수 있는 문자 넣기 ( EX: 서울시 몰랑 산후조리원, 경기도 몰랑 산후조리원)
```
## 크롤링 과정

```
1. 포스트 링크 추출 ( 게시판으로 부터 링크 추출, 포스트 ID로 접속시 장애가 많음)
2. 포스트 링크로부터 산후조리원 정보 추출 ( 이름, 주소, 연락처, 홈페이지 )
3. 중복처리
4. 저장
5. 산후조리원 주소로부터 네이버 맵 URL 추출
```

**Comment by dobestan** [comment]
thanks :) @wikibootup

**Comment by dobestan** [comment]
저는 개인적으로 생각했던게 

```
$ pip install maternity
```

로 설치할 수 있도록 한번 모듈로 만들어보고 싶었거든요. 그래서 지금 그렇게 진행을 하고 있는데, 

크롤링에 대한 부분은 형이 위에서 언급한거랑 유사한데 설계를 좀 멋지게 해보고 싶었어요. 일단 인터페이스 객체 하나 만들어서 각각 사이트에 대한 크롤링/파싱 구현은 따로 상속받아서 하는걸로?

어떻게 생각하세요?
